# Generated by Django 5.1.3 on 2025-07-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolionews', '0002_alter_article_options_remove_article_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='ticker',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
